_target_: gslm.u2s.dataset.datamodule.u2sDataModule
_recursive_: false
cfg:
  sample_rate: 22_050
  train_dataset:
    _target_: gslm.u2s.dataset.fairseq_manifest_dataset.FairseqManifestDataset
    manifest_path: /work/ge43/e43010/GSLM/manifest/train.tsv
    resampled_sr: 22_050
    extracted_feature_path: /work/ge43/e43010/GSLM/quantized/quantized_train
  val_dataset:
    _target_: gslm.u2s.dataset.fairseq_manifest_dataset.FairseqManifestDataset
    manifest_path: /work/ge43/e43010/GSLM/manifest/valid.tsv
    resampled_sr: 22_050
    extracted_feature_path: /work/ge43/e43010/GSLM/quantized/quantized_valid
  data:
    segment_size:
      train: 50
      val: -1
    train_batch_size: 24
    val_batch_size: 1
    target_feature:
      key: input_feature
      samples_per_sec: 50
      bias: 0.0025
  xvector:
    model:
      _target_: speechbrain.pretrained.EncoderClassifier.from_hparams
      source: "speechbrain/spkrec-xvect-voxceleb"
    sr: 16_000
  use_pitch: false
